#!/usr/bin/perl -T
#
# This is a trivial socket listener for rpm-ostree-toolbox event-driven
# builds. We get invoked via systemd with our stdin tied to a socket.
# The remote client gives us one branch name per line; we simply sanitize
# and, if a legitimate branch-like name, output it to stdout (which
# should be journald).
#
use strict;
use warnings;

use FileHandle;
STDOUT->autoflush(1);

while (my $line = <STDIN>) {
    # Remove trailing LF and, yes, CR: we'll never see that in regular use,
    # but telnet (as in 'telnet HOST PORT', for testing) sends \r\n.
    chomp $line;
    $line =~ tr/\r//d;

    # Sanitize input. For our purposes, require branch names to be
    # alphanumeric plus slash, dot, underscore, hyphen. Not quite
    # the same as the full git rules (see git-check-ref-format)
    # but good enough for us.
    if ($line =~ m|^([\w/._-]{1,90})$|) {
        print "branch:$1\n";
    }
    else {
        print "INVALID-INPUT\n";
    }
}
