#!/usr/bin/env python
# Copyright (C) 2014 Colin Walters <walters@verbum.org>, Andy Grimm <agrimm@redhat.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

import os
import sys

from rpmostreecompose import imagefactory, installer, treecompose

if __name__ == '__main__':
    print "%r" % (sys.argv, )
    cmd = sys.argv.pop(1)
    if cmd == 'imagefactory':
        imagefactory.main()
    elif cmd == 'installer':
        installer.main()
    elif cmd == 'treecompose':
        treecompose.main()
    else:
        sys.stderr.write('Unknown builtin: %s\n' % (cmd,))
        sys.exit(1)

